CREATE TABLE audit_logs
(

    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    username character varying(255) NOT NULL ,
    action character varying(255)  NOT NULL,
    old_value character varying(255)  ,
    new_value character varying(255)  ,
    entity character varying(255)  NOT NULL,
    params character varying(255)  ,
    timestamp TIMESTAMP      NOT NULL

);